[colors.bright]
cyan = "#89b482"
magenta = "#d3869b"
white = "#d4be98"
blue = "#7daea3"
black = "#665c54"
green = "#a9b665"
red = "#ea6962"
yellow = "#d8a657"

[colors.cursor]
cursor = "#d4be98"
text = "#32302f"

[colors.normal]
cyan = "#89b482"
magenta = "#d3869b"
white = "#d4be98"
blue = "#7daea3"
black = "#665c54"
green = "#a9b665"
red = "#ea6962"
yellow = "#d8a657"

[colors.selection]
text = "#45403d"
background = "#504945"

[colors.primary]
foreground = "#d4be98"
background = "#32302f"
